sources:
  picoruby_trunk:
    branch: master

  mruby_trunk:
    branch: master

  cruby_trunk:
    branch: master

  rurema:
    doctree_path: ~/dev/src/github.com/rurema/doctree
    version: "3.3.0"

  picoruby_docs:
    repo_path: ~/dev/src/github.com/picoruby/picoruby
